upload-dir: '.'

convert-options:
    quality: 80
    method: 6
    low-memory: true
    metadata: 'none'        # Valid values: all, none, exif, icc, xmp

    converters:
        -
            converter: 'cwebp'
            options:
                use-nice: true

        - imagick

        -
            converter: 'gd'
            options:
                skip-pngs: true

        -
            converter: 'ewww'
            options:
                key: 'key1'

        -
            converter: 'ewww'
            options:
                key: 'key2'
